package uk.gov.justice.digital.hmpps.visitscheduler.dto.enums

@Suppress("unused")
enum class EventAuditType {
  RESERVED_VISIT,
  CHANGING_VISIT,
  MIGRATED_VISIT,
  BOOKED_VISIT,
  UPDATED_VISIT,
  CANCELLED_VISIT,
  NON_ASSOCIATION_EVENT,
  PRISONER_RELEASED_EVENT,
  PRISONER_RECEIVED_EVENT,
  PRISONER_RESTRICTION_CHANGE_EVENT,
  PRISONER_ALERTS_UPDATED_EVENT,
  PRISON_VISITS_BLOCKED_FOR_DATE,
  SESSION_VISITS_BLOCKED_FOR_DATE,
  IGNORE_VISIT_NOTIFICATIONS_EVENT,
  PERSON_RESTRICTION_UPSERTED_EVENT,
  VISITOR_RESTRICTION_UPSERTED_EVENT,
  VISITOR_UNAPPROVED_EVENT,
  UPDATED_NON_ASSOCIATION_VISIT_EVENT,
  CANCELLED_NON_ASSOCIATION_VISIT_EVENT,
  IGNORED_NON_ASSOCIATION_VISIT_NOTIFICATIONS_EVENT,
  PAIRED_VISIT_CANCELLED_IGNORED_OR_UPDATED_EVENT,
}
