package uk.gov.justice.digital.hmpps.visitscheduler.dto.enums

@Suppress("unused")
enum class PrisonerSupportedAlertCodeType(val type: String, val description: String) {
  C1("Child Communication Measures", "L1 Restriction No contact with any child"),
  C2("Child Communication Measures", "L2 Written Contact with Children only"),
  C3("Child Communication Measures", "L3 Monitored Contact written or phone"),
  C4("Child Communication Measures", "L4 No Restrictions (named child only)"),
  CC1("Child Communication Measures", "Child contact L1"),
  CC2("Child Communication Measures", "Child contact L2"),
  CC3("Child Communication Measures", "Child contact L3"),
  CC4("Child Communication Measures", "Child contact L4"),
  CPC("Child Communication Measures", "PPRC"),
  CPRC("Child Communication Measures", "Potential PPRC"),
  ONCR("Other", "No-contact request"),
  RCDR("Risk", "Quarantined - Communicable Disease Risk"),
  RCP("Risk", "Children on CP Register"),
  RCS("Risk", "Risk to Children - Custody"),
  RDV("Risk", "Domestic Violence Perpetrator"),
  RKS("Risk", "Risk to Known Adult - Custody"),
  RSP("Risk", "Stalking Perpetrator"),
  SC("Sexual Offence", "Risk to Children"),
  SO("Sexual Offence", "Sexual Offence Not on Sex Offender Reg"),
  SONR("Sexual Offence", "Sex offender not required to register"),
  SOR("Sexual Offence", "Registered sex offender"),
  SR("Sexual Offence", "On Sex Offender Register"),
  SSHO("Sexual Offence", "RSHO or SRO"),
  UPIU("COVID unit management", "Protective Isolation Unit"),
  URCU("COVID unit management", "Reverse Cohorting Unit"),
  URS("COVID unit management", "Refusing to shield"),
  USU("COVID unit management", "Shielding Unit"),
  XCC("Security", "PSO4400 CH1 Children"),
  XCH("Security", "PSO4400 CH2 Harassment"),
  XCSEA("Security", "Child Sexual Exploitation Abuse"),
  XRF("Security", "Risk to Females"),
  XSO("Security", "Sex Offender"),
}
