CREATE TABLE prison_wing (
        id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "name" varchar(255) NOT NULL,
        prison_id varchar(255) NOT NULL,
        CONSTRAINT prison_wing_pkey PRIMARY KEY (id)
);

CREATE TABLE session_to_wing (
    session_template_id int8 NOT NULL,
    wing_id int8 NOT NULL,
    CONSTRAINT session_to_wing_pkey PRIMARY KEY (session_template_id, wing_id),
    CONSTRAINT template_must_exist  FOREIGN KEY (session_template_id) REFERENCES session_template(id),
    CONSTRAINT wing_must_exist      FOREIGN KEY (wing_id) REFERENCES prison_wing(id)
);

